cloud:
  aws:
    region:
      static: eu-central-1
      auto: true
    stack:
      auto: true
    credentials:
      acccessKey: AKIAV64VOPQ7I6GH67HS
      secretKey: 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